USE WAREHOUSE COMPUTE_WH;

CREATE OR REPLACE TABLE FLEET_DEMOS.ROUTE_DEVIATIONS.TRIP_ACTUAL_METRICS AS
WITH valid_trips AS (
    SELECT DISTINCT TRIP_ID
    FROM SYNTHETIC_DATASETS.FLEET_INTELLIGENCE.FACT_TRUCK_TELEMETRY
    WHERE REGEXP_LIKE(TRIP_ID, '^[0-9]{8}-TRK-[0-9]{5}-[0-9]{2}$')
),
moving_intervals AS (
    SELECT 
        t.TRIP_ID, t.TS, t.STATUS,
        LEAD(t.TS) OVER (PARTITION BY t.TRIP_ID ORDER BY t.TS) AS next_ts
    FROM SYNTHETIC_DATASETS.FLEET_INTELLIGENCE.FACT_TRUCK_TELEMETRY t
    JOIN valid_trips v ON t.TRIP_ID = v.TRIP_ID
),
trip_durations AS (
    SELECT 
        TRIP_ID,
        SUM(CASE WHEN STATUS = 'MOVING' AND next_ts IS NOT NULL THEN TIMESTAMPDIFF('SECOND', TS, next_ts) ELSE 0 END) AS MOVING_DURATION_SEC,
        SUM(CASE WHEN next_ts IS NOT NULL THEN TIMESTAMPDIFF('SECOND', TS, next_ts) ELSE 0 END) AS TOTAL_DURATION_SEC
    FROM moving_intervals
    GROUP BY TRIP_ID
),
trip_meta AS (
    SELECT 
        t.TRIP_ID,
        ANY_VALUE(t.TRUCK_ID) AS TRUCK_ID,
        ANY_VALUE(t.DRIVER_ID) AS DRIVER_ID,
        MIN(t.TS) AS ACTUAL_START_TS,
        MAX(t.TS) AS ACTUAL_END_TS,
        COUNT(*) AS POINT_COUNT,
        TO_GEOGRAPHY(
            OBJECT_CONSTRUCT(
                'type', 'LineString',
                'coordinates', ARRAY_AGG(ARRAY_CONSTRUCT(ST_X(GEOMETRY), ST_Y(GEOMETRY))) WITHIN GROUP (ORDER BY TS)
            )::VARCHAR
        ) AS ACTUAL_PATH
    FROM SYNTHETIC_DATASETS.FLEET_INTELLIGENCE.FACT_TRUCK_TELEMETRY t
    JOIN valid_trips v ON t.TRIP_ID = v.TRIP_ID
    GROUP BY t.TRIP_ID
    HAVING COUNT(*) >= 2
)
SELECT
    m.TRIP_ID,
    m.TRUCK_ID,
    m.DRIVER_ID,
    'TRK-' || LPAD(REPLACE(m.TRUCK_ID, 'TRK-', ''), 5, '0') AS TRUCK_ID_NORMALIZED,
    TO_DATE(LEFT(m.TRIP_ID, 8), 'YYYYMMDD') AS TRIP_DATE,
    CAST(SPLIT_PART(m.TRIP_ID, '-', 4) AS INTEGER) AS TRIP_SEQ,
    m.ACTUAL_START_TS,
    m.ACTUAL_END_TS,
    d.TOTAL_DURATION_SEC,
    ROUND(d.TOTAL_DURATION_SEC / 60.0, 2) AS TOTAL_DURATION_MIN,
    d.MOVING_DURATION_SEC AS ACTUAL_DURATION_SEC,
    ROUND(d.MOVING_DURATION_SEC / 60.0, 2) AS ACTUAL_DURATION_MIN,
    m.POINT_COUNT,
    m.ACTUAL_PATH
FROM trip_meta m
JOIN trip_durations d ON m.TRIP_ID = d.TRIP_ID;
