USE WAREHOUSE COMPUTE_WH;

CREATE OR REPLACE TABLE FLEET_DEMOS.ROUTE_DEVIATIONS.OD_EXPECTED_ROUTES AS
WITH unique_od_pairs AS (
    SELECT DISTINCT 
        ts.ORIGIN_ID, ts.DEST_ID,
        o.LNG AS ORIGIN_LNG, o.LAT AS ORIGIN_LAT,
        o.NAME AS ORIGIN_NAME, o.CITY AS ORIGIN_CITY,
        d.LNG AS DEST_LNG, d.LAT AS DEST_LAT,
        d.NAME AS DEST_NAME, d.CITY AS DEST_CITY
    FROM SYNTHETIC_DATASETS.FLEET_INTELLIGENCE.TRIP_SCHEDULE ts
    JOIN SYNTHETIC_DATASETS.FLEET_INTELLIGENCE.GERMANY_DESTINATIONS o ON ts.ORIGIN_ID = o.ID
    JOIN SYNTHETIC_DATASETS.FLEET_INTELLIGENCE.GERMANY_DESTINATIONS d ON ts.DEST_ID = d.ID
    WHERE ts.ORIGIN_ID IS NOT NULL AND ts.DEST_ID IS NOT NULL
)
SELECT 
    p.ORIGIN_ID, p.DEST_ID,
    p.ORIGIN_LNG, p.ORIGIN_LAT, p.ORIGIN_NAME, p.ORIGIN_CITY,
    p.DEST_LNG, p.DEST_LAT, p.DEST_NAME, p.DEST_CITY,
    HAVERSINE(p.ORIGIN_LAT, p.ORIGIN_LNG, p.DEST_LAT, p.DEST_LNG) AS STRAIGHT_LINE_DISTANCE_KM,
    ROUND(c.ROAD_DISTANCE_M / 1000, 2) AS EXPECTED_DISTANCE_KM,
    c.DURATION_SECONDS AS EXPECTED_DURATION_SEC,
    ROUND(c.DURATION_SECONDS / 60.0, 2) AS EXPECTED_DURATION_MIN,
    c.ROUTE_LINE AS EXPECTED_PATH
FROM unique_od_pairs p
JOIN FLEET_DEMOS.ROUTING.ROUTE_CACHE c 
    ON p.ORIGIN_ID = c.ORIGIN_ID AND p.DEST_ID = c.DEST_ID;
