USE WAREHOUSE COMPUTE_WH;

CREATE OR REPLACE TABLE FLEET_DEMOS.ROUTE_DEVIATIONS.TRIP_DEVIATION_ANALYSIS AS
SELECT
    a.TRIP_ID,
    a.TRUCK_ID,
    a.DRIVER_ID,
    a.TRIP_DATE,
    s.ROUTE_VARIATION,
    s.ROUTE_DEVIATION_FACTOR,
    s.TRIP_TYPE,

    ROUND(e.EXPECTED_DISTANCE_KM * s.ROUTE_DEVIATION_FACTOR, 2) AS ACTUAL_DISTANCE_KM,
    a.ACTUAL_DURATION_MIN,
    a.TOTAL_DURATION_MIN,
    a.ACTUAL_START_TS,
    a.ACTUAL_END_TS,
    a.POINT_COUNT,

    e.EXPECTED_DISTANCE_KM,
    e.EXPECTED_DURATION_MIN,
    e.STRAIGHT_LINE_DISTANCE_KM,
    e.ORIGIN_NAME, e.ORIGIN_CITY,
    e.DEST_NAME, e.DEST_CITY,

    ROUND(e.EXPECTED_DISTANCE_KM * s.ROUTE_DEVIATION_FACTOR - e.EXPECTED_DISTANCE_KM, 2) AS DISTANCE_DEVIATION_KM,
    ROUND((s.ROUTE_DEVIATION_FACTOR - 1) * 100, 2) AS DISTANCE_DEVIATION_PCT,
    ROUND(a.ACTUAL_DURATION_MIN - e.EXPECTED_DURATION_MIN, 2) AS DURATION_DEVIATION_MIN,
    ROUND((a.ACTUAL_DURATION_MIN - e.EXPECTED_DURATION_MIN) / NULLIF(e.EXPECTED_DURATION_MIN, 0) * 100, 2) AS DURATION_DEVIATION_PCT,

    CASE WHEN ABS(s.ROUTE_DEVIATION_FACTOR - 1) > 0.20 THEN TRUE ELSE FALSE END AS IS_DISTANCE_DEVIATION,
    CASE WHEN ABS((a.ACTUAL_DURATION_MIN - e.EXPECTED_DURATION_MIN) / NULLIF(e.EXPECTED_DURATION_MIN, 0)) > 0.20 THEN TRUE ELSE FALSE END AS IS_DURATION_DEVIATION,
    CASE WHEN ABS(s.ROUTE_DEVIATION_FACTOR - 1) > 0.20
           OR ABS((a.ACTUAL_DURATION_MIN - e.EXPECTED_DURATION_MIN) / NULLIF(e.EXPECTED_DURATION_MIN, 0)) > 0.20
         THEN TRUE ELSE FALSE END AS IS_ROUTE_DEVIATION,

    a.ACTUAL_PATH,
    e.EXPECTED_PATH

FROM FLEET_DEMOS.ROUTE_DEVIATIONS.TRIP_ACTUAL_METRICS a
JOIN (
    SELECT *, ROW_NUMBER() OVER (PARTITION BY TRUCK_ID, TRIP_DATE ORDER BY SHIFT_START_TIME) - 1 AS trip_seq
    FROM SYNTHETIC_DATASETS.FLEET_INTELLIGENCE.TRIP_SCHEDULE
) s ON s.TRUCK_ID = a.TRUCK_ID_NORMALIZED AND s.TRIP_DATE = a.TRIP_DATE AND s.trip_seq = a.TRIP_SEQ
JOIN FLEET_DEMOS.ROUTE_DEVIATIONS.OD_EXPECTED_ROUTES e ON s.ORIGIN_ID = e.ORIGIN_ID AND s.DEST_ID = e.DEST_ID;
