USE WAREHOUSE COMPUTE_WH;

CREATE OR REPLACE TABLE FLEET_DEMOS.ROUTE_DEVIATIONS.DRIVER_DEVIATION_SUMMARY AS
SELECT
    d.TRUCK_ID,
    d.DRIVER_ID,
    f.DRIVER_PROFILE,
    f.TRUCK_TYPE,
    f.HOME_CITY,
    COUNT(*) AS TOTAL_TRIPS,
    SUM(CASE WHEN d.IS_ROUTE_DEVIATION THEN 1 ELSE 0 END) AS DEVIATION_TRIPS,
    ROUND(SUM(CASE WHEN d.IS_ROUTE_DEVIATION THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS DEVIATION_RATE_PCT,
    ROUND(SUM(CASE WHEN d.IS_ROUTE_DEVIATION THEN d.DISTANCE_DEVIATION_KM ELSE 0 END), 2) AS TOTAL_EXCESS_KM,
    ROUND(SUM(CASE WHEN d.IS_ROUTE_DEVIATION THEN d.DURATION_DEVIATION_MIN ELSE 0 END), 2) AS TOTAL_TIME_LOST_MIN,
    ROUND(AVG(d.DISTANCE_DEVIATION_PCT), 2) AS AVG_DISTANCE_DEVIATION_PCT,
    ROUND(AVG(d.DURATION_DEVIATION_PCT), 2) AS AVG_DURATION_DEVIATION_PCT,
    MAX(d.DISTANCE_DEVIATION_PCT) AS MAX_DISTANCE_DEVIATION_PCT,
    MAX(d.DURATION_DEVIATION_PCT) AS MAX_DURATION_DEVIATION_PCT
FROM FLEET_DEMOS.ROUTE_DEVIATIONS.TRIP_DEVIATION_ANALYSIS d
JOIN SYNTHETIC_DATASETS.FLEET_INTELLIGENCE.TRUCK_FLEET f
    ON 'TRK-' || LPAD(REPLACE(d.TRUCK_ID, 'TRK-', ''), 5, '0') = f.TRUCK_ID
GROUP BY d.TRUCK_ID, d.DRIVER_ID, f.DRIVER_PROFILE, f.TRUCK_TYPE, f.HOME_CITY;
