USE WAREHOUSE COMPUTE_WH;

CREATE OR REPLACE TABLE FLEET_DEMOS.ROUTE_DEVIATIONS.DAILY_DEVIATION_TRENDS AS
SELECT
    TRIP_DATE,
    DAYNAME(TRIP_DATE) AS DAY_OF_WEEK,
    COUNT(*) AS TOTAL_TRIPS,
    SUM(CASE WHEN IS_ROUTE_DEVIATION THEN 1 ELSE 0 END) AS DEVIATION_TRIPS,
    ROUND(SUM(CASE WHEN IS_ROUTE_DEVIATION THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS DEVIATION_RATE_PCT,
    ROUND(SUM(DISTANCE_DEVIATION_KM), 2) AS TOTAL_EXCESS_DISTANCE_KM,
    ROUND(SUM(DURATION_DEVIATION_MIN), 2) AS TOTAL_EXCESS_DURATION_MIN,
    ROUND(AVG(DISTANCE_DEVIATION_PCT), 2) AS AVG_DISTANCE_DEVIATION_PCT,
    ROUND(AVG(DURATION_DEVIATION_PCT), 2) AS AVG_DURATION_DEVIATION_PCT
FROM FLEET_DEMOS.ROUTE_DEVIATIONS.TRIP_DEVIATION_ANALYSIS
GROUP BY TRIP_DATE;
